# Generated by Django 6.0.3 on 2026-07-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_gamingproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='landing_page_url',
            field=models.URLField(blank=True, help_text="Optional. If set, this squad's card on the main site becomes a link to this page (e.g. https://vicegamers.com/gta/). Leave it empty and the card renders unlinked, as it does today.", null=True, verbose_name='Landing page URL'),
        ),
    ]
